//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMEnterpriseDB.Models
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class AdvancePaymentMaster
    {
        public int AdPaymentID { get; set; }
        public int EmployeeID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<decimal> EMI { get; set; }
        public Nullable<int> Months { get; set; }
        public Nullable<int> DeductionsDone { get; set; }
        public Nullable<decimal> DeductedAmount { get; set; }
        public Nullable<int> Status { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<int> EmployeeType { get; set; }
    }
}
