//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMEnterpriseDB.Models
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class AppUsers
    {
        public int AppUserID { get; set; }
        public Nullable<int> UserType { get; set; }
        public Nullable<int> UserID { get; set; }
        public string UUID { get; set; }
        public Nullable<System.DateTime> LastActive { get; set; }
        public string FCMToken { get; set; }
        public Nullable<int> SBranchID { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
