//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMEnterpriseDB.Models
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class AssignmentSubmissions
    {
        public int AssResponseID { get; set; }
        public Nullable<int> AssignmentID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<System.DateTime> SubmissionDate { get; set; }
        public string Description { get; set; }
        public Nullable<int> Status { get; set; }
        public string Reason { get; set; }
        public string Comments { get; set; }
        public string Attachments { get; set; }
        public string Grade { get; set; }
    }
}
