//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMEnterpriseDB.Models
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class AssignmentMaster
    {
        public int ID { get; set; }
        public int TeacherID { get; set; }
        public int ClassID { get; set; }
        public int SectionID { get; set; }
        public int SubjectID { get; set; }
        public int ChapterID { get; set; }
        public int TopicID { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> Enddate { get; set; }
        public Nullable<int> GracedDays { get; set; }
        public string TaskType { get; set; }
        public string Title { get; set; }
        public string Detail { get; set; }
        public string Attachments { get; set; }
        public Nullable<bool> SendMail { get; set; }
        public System.DateTime CreatedOn { get; set; }
    }
}
