//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMEnterpriseDB.Models
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class AttandanceDeviceDetails
    {
        public int DeviceID { get; set; }
        public string DeviceSerial { get; set; }
        public Nullable<int> SBranchID { get; set; }
    }
    [Serializable]
    public class AttendanceStates
    {
        public int AttStateCode { get; set; }
        public string AttStateName { get; set; }

    }
    [Serializable]
    public class VerificationMode
    {
        public int VerifyMethodCode { get; set; }
        public string VerifyMethodName { get; set; }
    }
}
