//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMEnterpriseDB.Models
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class BookCopyDetail
    {
        public int CopyID { get; set; }
        public Nullable<int> BookID { get; set; }
        public string BarCode { get; set; }
        public string RFID { get; set; }
        public Nullable<int> AStatus { get; set; }
        public string Code { get; set; }
    }
}
