//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMEnterpriseDB.Models
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class BookMaster
    {
        public int BookID { get; set; }
        public string Title { get; set; }
        public string Publisher { get; set; }
        public Nullable<int> BayID { get; set; }
        public string Description { get; set; }
        public Nullable<int> Copies { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Author { get; set; }
        public string Image { get; set; }
        public string CategoryIDs { get; set; }
        public string ClassesIDs { get; set; }
        public string ISBN { get; set; }
        public string ISBN13 { get; set; }
        public Nullable<int> SBranchID { get; set; }
        public string BookCode { get; set; }
        public Nullable<int> IssueDays { get; set; }
    }
}
