//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMEnterpriseDB.Models
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class C_MasterSettings
    {
        public int MasterDetailsId { get; set; }
        public int IsAlphaNumericEmployeeCode { get; set; }
        public int IsFixedShift { get; set; }
        public string ShiftBeginTime { get; set; }
        public string ShiftEndTime { get; set; }
        public int IsDeviceCodeSame { get; set; }
        public string AttendanceYearStartMonth { get; set; }
        public string AttendanceYearStartDate { get; set; }
        public Nullable<int> ExtraHourShiftExpires { get; set; }
        public string LiecenceKey { get; set; }
        public Nullable<int> PunchBeginDuration { get; set; }
        public string Version { get; set; }
        public int IsAutoBackUp { get; set; }
        public string AutoBackuppath { get; set; }
        public Nullable<int> BackupDays { get; set; }
        public string LastBackUpDate { get; set; }
        public Nullable<int> MinDiffBetweenTwoPunch { get; set; }
        public Nullable<int> IsAutoShift { get; set; }
        public string C1 { get; set; }
        public string C2 { get; set; }
        public string C3 { get; set; }
        public string C4 { get; set; }
        public string C5 { get; set; }
        public string C6 { get; set; }
        public string C7 { get; set; }
        public string C8 { get; set; }
        public string C9 { get; set; }
        public string C10 { get; set; }
        public string C11 { get; set; }
        public string C12 { get; set; }
        public string C13 { get; set; }
        public string C14 { get; set; }
        public string C15 { get; set; }
        public string MemoLateEarlySubject { get; set; }
        public string MemoMissedPunchSubject { get; set; }
        public string MemoSignature { get; set; }
        public string MemoAbsentText { get; set; }
        public string MemoLateEarlyText { get; set; }
        public string MemoMissedPunchText { get; set; }
        public string MemoAbsentSubject { get; set; }
        public string EmployeePhotoPath { get; set; }
        public string VisitorPhotoPath { get; set; }
        public string VisitorFingerPrintPath { get; set; }
        public string VehiclePhotoPath { get; set; }
        public Nullable<int> IsAutoClearLogs { get; set; }
        public string MemoHalfDayForLateEarlySubject { get; set; }
        public string MemoHalfDayForLateEarlyText { get; set; }
    }
}
