//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMEnterpriseDB.Models
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class ChapterMaster
    {
        public int ChapterID { get; set; }
        public Nullable<int> ClassID { get; set; }
        public Nullable<int> GroupID { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public string ChapterName { get; set; }
        public string ChapterDescription { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<int> SequenceNo { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> SBranchID { get; set; }
    }
}
