//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMEnterpriseDB.Models
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class Class_Sections
    {
        public int ID { get; set; }
        public Nullable<int> ClassID { get; set; }
        public string Name { get; set; }
        public Nullable<int> GroupID { get; set; }
        public Nullable<int> TeacherID { get; set; }
        public Nullable<int> Capacity { get; set; }
        public Nullable<int> RoomID { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
