//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMEnterpriseDB.Models
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class Class_Merge_Master
    {
        public int ClassMergeID { get; set; }
        public Nullable<int> FirstSectionID { get; set; }
        public Nullable<int> SecondSectionID { get; set; }
        public Nullable<int> RoomID { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public Nullable<int> DayID { get; set; }
        public Nullable<int> PeriodID { get; set; }
        public Nullable<int> TeacherID { get; set; }
    }
}
