//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMEnterpriseDB.Models
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class ClassMaster
    {
        public int ClassID { get; set; }
        public string ClassName { get; set; }
        public Nullable<int> EducationLevelID { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> SBranchID { get; set; }
        public Nullable<int> SequenceNo { get; set; }
    
        public virtual EducationLevelMaster EducationLevelMaster { get; set; }
    }
    [Serializable]
    public class Time_Table_Master
    {
        public int EducationLevelID { get; set; }
        public int ClassID { get; set; }
        public int SectionID { get; set; }
        public int PeriodID { get; set; }
        public int MondaySubjectID { get; set; }
        public int MondayTeacherID { get; set; }
        public int TuesdaySubjectID { get; set; }
        public int TuesdayTeacherID { get; set; }
        public int WednesdaySubjectID { get; set; }
        public int WednesdayTeacherID { get; set; }
        public int ThursdaySubjectID { get; set; }
        public int ThursdayTeacherID { get; set; }
        public int FridaySubjectID { get; set; }
        public int FridayTeacherID { get; set; }
        public int SaturdaySubjectID { get; set; }
        public int SaturdayTeacherID { get; set; }
        public int SBranchID { get; set; }

    }
}
