//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMEnterpriseDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceOperationLog
    {
        public int DeviceOperationLogId { get; set; }
        public Nullable<int> DeviceOperationLogCode { get; set; }
        public Nullable<System.DateTime> DeviceOperationLogExecutedOn { get; set; }
        public string SerialNumber { get; set; }
    }
}
