//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMEnterpriseDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceErrorMessages
    {
        public int DeviceErrorMessageId { get; set; }
        public string SerialNumber { get; set; }
        public string ErrorMessage { get; set; }
        public string LogStream { get; set; }
        public string CreatedDate { get; set; }
    }
}
