//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMEnterpriseDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceOperationLogType
    {
        public int OperationLogTypeId { get; set; }
        public Nullable<int> OperationLogTypeCode { get; set; }
        public string OperationLogTypeName { get; set; }
    }
}
