//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMEnterpriseDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceLogs_3_2017
    {
        public int DeviceLogId { get; set; }
        public Nullable<System.DateTime> DownloadDate { get; set; }
        public Nullable<int> DeviceId { get; set; }
        public string UserId { get; set; }
        public System.DateTime LogDate { get; set; }
        public string Direction { get; set; }
        public string AttDirection { get; set; }
        public string C1 { get; set; }
        public string C2 { get; set; }
        public string C3 { get; set; }
        public string C4 { get; set; }
        public string C5 { get; set; }
        public string C6 { get; set; }
        public string C7 { get; set; }
        public string WorkCode { get; set; }
        public Nullable<int> UpdateFlag { get; set; }
    }
}
