//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMEnterpriseDB.Models
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class Devices
    {
        public int DeviceId { get; set; }
        public string DeviceFName { get; set; }
        public string DeviceSName { get; set; }
        public string DeviceDirection { get; set; }
        public string SerialNumber { get; set; }
        public string ConnectionType { get; set; }
        public string IpAddress { get; set; }
        public string BaudRate { get; set; }
        public string CommKey { get; set; }
        public string ComPort { get; set; }
        public Nullable<System.DateTime> LastLogDownloadDate { get; set; }
        public string C1 { get; set; }
        public string C2 { get; set; }
        public string C3 { get; set; }
        public string C4 { get; set; }
        public string C5 { get; set; }
        public string C6 { get; set; }
        public string C7 { get; set; }
        public string TransactionStamp { get; set; }
        public Nullable<System.DateTime> LastPing { get; set; }
        public string DeviceType { get; set; }
        public string OpStamp { get; set; }
        public Nullable<int> DownLoadType { get; set; }
        public string Timezone { get; set; }
        public string DeviceLocation { get; set; }
        public string TimeOut { get; set; }
    }
    [Serializable]
    public class ParallelDatabaseDetails
    {
        public int IsParallelDatabaseDowload { get; set; }
        public string DatabaseType { get; set; }
        public string Service { get; set; }
        public string Port { get; set; }
        public string ServerName { get; set; }
        public string DatabaseName { get; set; }
        public string DatabaseUserName { get; set; }
        public string DatabasePassword { get; set; }
        public string TableName { get; set; }
        public string EmployeeCode { get; set; }
        public string LogDate { get; set; }
        public string Direction { get; set; }
        public string WorkCode { get; set; }
        public int IsReservedField1 { get; set; }
        public int IsReservedField2 { get; set; }
        public string ReservedField1 { get; set; }
        public string ReservedField1Value { get; set; }
        public string ReservedField2 { get; set; }
        public string ReservedField2Value { get; set; }
        public string LogTime { get; set; }
        public string LogDateTime { get; set; }
        public string LogTimeFormat { get; set; }
        public string LogDateTimeFormat { get; set; }
        public string LogDateFormat { get; set; }
        public string InValue { get; set; }
        public string OutValue { get; set; }
        public string SerialNumber { get; set; }

    }
    [Serializable]
    public class ParallelAttLogExportDetails
    {
        public int IsParallelDatabaseDowload { get; set; }
        public string DatabaseType { get; set; }
        public string Service { get; set; }
        public string Port { get; set; }
        public string ServerName { get; set; }
        public string DatabaseName { get; set; }
        public string DatabaseUserName { get; set; }
        public string DatabasePassword { get; set; }
        public string TableName { get; set; }
        public string DBPath { get; set; }
        public string AttendanceDate { get; set; }
        public string AttendanceDateFormat { get; set; }
        public string EmployeeCode { get; set; }
        public string Company { get; set; }
        public string Category { get; set; }
        public string Department { get; set; }
        public string Designation { get; set; }
        public string EmployementType { get; set; }
        public string InDate { get; set; }
        public string InDateFormat { get; set; }
        public string InTime { get; set; }
        public string InTimeFormat { get; set; }
        public string InDevice { get; set; }
        public string InLocation { get; set; }
        public string OutDate { get; set; }
        public string OutDateFormat { get; set; }
        public string OutTime { get; set; }
        public string OutTimeFormat { get; set; }
        public string OutDevice { get; set; }
        public string OutLocation { get; set; }
        public string Status { get; set; }
        public string StatusCode { get; set; }
        public string Duration { get; set; }
        public string LateBy { get; set; }
        public string EarlyBy { get; set; }
        public string OverTime { get; set; }
        public string IsOnLeave { get; set; }
        public string LeaveType { get; set; }
        public string IsOnOD { get; set; }
        public string ODDuration { get; set; }
        public string PunchRecords { get; set; }
        public string ShiftName { get; set; }
        public int IsReservedField1 { get; set; }
        public int IsReservedField2 { get; set; }
        public int IsReservedField3 { get; set; }
        public string ReservedField1 { get; set; }
        public string ReservedField1Value { get; set; }
        public string ReservedField2 { get; set; }
        public string ReservedField2Value { get; set; }
        public string ReservedField3 { get; set; }
        public string ReservedField3Value { get; set; }

    }
}
