//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMEnterpriseDB.Models
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class DriverConductorDetails
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string LicenceNo { get; set; }
        public string CurrentAddress { get; set; }
        public string PermanentAddress { get; set; }
        public string ContactNumber { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<int> Type { get; set; }
        public string Image { get; set; }
        public Nullable<bool> isVarified { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> SBranchID { get; set; }
        public Nullable<System.DateTime> DOJ { get; set; }
    }
}
