//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMEnterpriseDB.Models
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class EmployeeEducationDetails
    {
        public int EmpEduID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string Qualification { get; set; }
        public string Stream { get; set; }
        public string InstituteName { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string PassingYear { get; set; }
        public Nullable<decimal> Percentage { get; set; }
        public string Grade { get; set; }
    }
}
