//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMEnterpriseDB.Models
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class EmployeeMaster
    {
        public int EmployeeID { get; set; }
        public Nullable<int> SBranchID { get; set; }
        public string EmployeeName { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<int> Gender { get; set; }
        public Nullable<int> Nationality { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> ReligionID { get; set; }
        public Nullable<System.DateTime> DOJ { get; set; }
        public string EmailID { get; set; }
        public string BloodGroup { get; set; }
        public Nullable<int> MaritalStatus { get; set; }
        public Nullable<int> MotherTongueID { get; set; }
        public string MobileNumber { get; set; }
        public string LandLineNumber { get; set; }
        public string PassportNo { get; set; }
        public string FatherHubName { get; set; }
        public string Padd_HouseNo { get; set; }
        public string Padd_Street { get; set; }
        public string Padd_Area { get; set; }
        public string Padd_Sector { get; set; }
        public string Padd_PinCode { get; set; }
        public string Padd_District { get; set; }
        public string Padd_State { get; set; }
        public string Padd_Country { get; set; }
        public string Cadd_HouseNo { get; set; }
        public string Cadd_Street { get; set; }
        public Nullable<int> Cadd_Area { get; set; }
        public string Cadd_Sector { get; set; }
        public string Cadd_PinCode { get; set; }
        public Nullable<int> Cadd_DistrictCode { get; set; }
        public Nullable<int> Cadd_StateCode { get; set; }
        public Nullable<int> Cadd_CountryCode { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public string Role { get; set; }
        public string AccessCardNo { get; set; }
        public string VehicleNo { get; set; }
        public string DriverName { get; set; }
        public string DriverMobileNo { get; set; }
        public Nullable<int> DesignationID { get; set; }
        public string AddressProof { get; set; }
        public string BirthCertificate { get; set; }
        public string CategoryCertificate { get; set; }
        public string Photo { get; set; }
        public string ExperienceCertificate { get; set; }
        public string RelievingCertificate { get; set; }
        public string PFDeclaration { get; set; }
        public string PANCardCopy { get; set; }
        public string BankAccountProof { get; set; }
        public string MedicalCertificate { get; set; }
        public string AppointmentLetter { get; set; }
        public string PANnumber { get; set; }
        public string PFNumber { get; set; }
        public string BankName { get; set; }
        public string IFSCCode { get; set; }
        public string AccountName { get; set; }
        public string AccountNumber { get; set; }
        public Nullable<int> VehicleRouteID { get; set; }
        public Nullable<int> StopID { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> EmployeeType { get; set; }
        public string AadharNumber { get; set; }
        public string LicenceNumber { get; set; }
    }
}
