//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMEnterpriseDB.Models
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class EmployeesBio
    {
        public int EmployeeBioId { get; set; }
        public int EmployeeId { get; set; }
        public string BioType { get; set; }
        public string BioVersion { get; set; }
        public int BioId { get; set; }
        public string Bio { get; set; }
    }
}
