//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMEnterpriseDB.Models
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class EmployeeLeaveTypeMaster
    {
        public int ELID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> LeaveTypeID { get; set; }
        public Nullable<decimal> YearlyQuota { get; set; }
        public Nullable<decimal> MonthlyQuota { get; set; }
    }
}
