//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMEnterpriseDB.Models
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class EmployeeTypeSalaryDetails
    {
        public int ETypeSTypeID { get; set; }
        public Nullable<int> EmployeeTypeID { get; set; }
        public Nullable<int> SalaryTypeID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> SBranchID { get; set; }
    }
}
