//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMEnterpriseDB.Models
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class EvaluationDetails
    {
        public int SubEvaluationID { get; set; }
        public Nullable<int> EvaluationID { get; set; }
        public Nullable<int> EvaluationType { get; set; }
        public string EvaluationName { get; set; }
        public Nullable<decimal> Weightage { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> EvaluationMonth { get; set; }
        public Nullable<int> SBranchID { get; set; }
        public Nullable<int> UserID { get; set; }
    }
}
