//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMEnterpriseDB.Models
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class ExamMaster
    {
        public int ExamID { get; set; }
        public Nullable<int> EvaluationID { get; set; }
        public Nullable<int> ClassID { get; set; }
        public Nullable<int> GroupID { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public Nullable<System.DateTime> ExamDate { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public Nullable<int> SBranchID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsApplicable { get; set; }
        public Nullable<decimal> MaxMarks { get; set; }
        public Nullable<decimal> PassMarks { get; set; }
        public Nullable<int> IsLocked { get; set; }
    }
}
