//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMEnterpriseDB.Models
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class ExpenceMaster
    {
        public int ExpenceID { get; set; }
        public string ReferanceNumber { get; set; }
        public string ExpenceTitle { get; set; }
        public Nullable<int> PaymentType { get; set; }
        public Nullable<int> PaymentMode { get; set; }
        public string Remark { get; set; }
        public Nullable<decimal> PaymentAmount { get; set; }
        public Nullable<int> PaymentStatus { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<int> SBranchID { get; set; }
        public Nullable<System.DateTime> EnteredDate { get; set; }
        public Nullable<int> ExpenceTypeID { get; set; }
    }
}
