//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMEnterpriseDB.Models
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class ExpenceTypeMaster
    {
        public int ExpenceTypeID { get; set; }
        public string ExpenceTypeName { get; set; }
        public Nullable<int> ExpenceTypeApplicable { get; set; }
        public string ChartColor { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<bool> IsBaseType { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
