//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMEnterpriseDB.Models
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class ExpenceBillImages
    {
        public int BillID { get; set; }
        public Nullable<int> ExpenceID { get; set; }
        public string BillFor { get; set; }
        public string ImageName { get; set; }
    }
}
