//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMEnterpriseDB.Models
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class FeeTypeMaster
    {
        public int FeeTypeID { get; set; }
        public string FeeTypeName { get; set; }
        public Nullable<int> FeeTypeApplicable { get; set; }
        public string ChartColor { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<bool> IsBaseType { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ShortName { get; set; }
        public Nullable<int> SBranchID { get; set; }
    }
}
