//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMEnterpriseDB.Models
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class Group_Subject
    {
        public int GroupID { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public Nullable<bool> IsOptionalSubject { get; set; }
        public int e { get; set; }
    }
}
