//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMEnterpriseDB.Models
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class HolidayMaster
    {
        public int HolidayID { get; set; }
        public Nullable<int> HolidayType { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> Classes { get; set; }
        public string Title { get; set; }
        public Nullable<int> Days { get; set; }
        public string HolidayDescription { get; set; }
        public Nullable<int> DayDuration { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> SBranchID { get; set; }
        public Nullable<bool> IsEmployee { get; set; }
        public Nullable<bool> IsStudents { get; set; }
        public Nullable<int> ISSMSSent { get; set; }
        public string SMSSentTo { get; set; }
        public string AssociatedIDs { get; set; }
    }
    [Serializable]
    public class Holiday_Classes
    {
        public int HolidayID { get; set; }
        public int ClassID { get; set; }
    }
}
