//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMEnterpriseDB.Models
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class Hostel_RoomTypeRateMaster
    {
        public int ID { get; set; }
        public Nullable<int> HostelID { get; set; }
        public Nullable<int> RoomTypeID { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<int> SBranchID { get; set; }
        public string RoomTypeName { get; set; }
        public Nullable<int> Capacity { get; set; }
    }
}
