//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMEnterpriseDB.Models
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class LeaveMaster
    {
        public int LeaveID { get; set; }
        public Nullable<int> ApplicantType { get; set; }
        public Nullable<int> LeaveType { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string LeaveReason { get; set; }
        public Nullable<int> ApplicantID { get; set; }
        public Nullable<int> IsApproved { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> SBranchID { get; set; }
        public Nullable<decimal> CLApplied { get; set; }
        public Nullable<decimal> ELApplied { get; set; }
        public Nullable<decimal> PLApplied { get; set; }
        public Nullable<int> EmployeeType { get; set; }
        public Nullable<decimal> LWPApplied { get; set; }
    }
}
