//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMEnterpriseDB.Models
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class LibraryIssueBooks
    {
        public int BookIssueID { get; set; }
        public Nullable<int> BookID { get; set; }
        public Nullable<int> CopyID { get; set; }
        public Nullable<int> IssueDays { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public string Remark { get; set; }
        public Nullable<int> LibraryIssueID { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
