//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMEnterpriseDB.Models
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class LibraryIssueRegister
    {
        public int IssueID { get; set; }
        public Nullable<int> BorrowerType { get; set; }
        public Nullable<int> BorrowerID { get; set; }
        public Nullable<int> ClassID { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<int> IssuedDays { get; set; }
        public Nullable<int> LibraryID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Remark { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> SessionID { get; set; }
    }
}
