//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMEnterpriseDB.Models
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class MailProcessingStatus
    {
        public int ID { get; set; }
        public Nullable<int> MailReqID { get; set; }
        public string Name { get; set; }
        public string EmailID { get; set; }
        public Nullable<int> Status { get; set; }
        public string IssueDescription { get; set; }
    }
}
