//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMEnterpriseDB.Models
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class MailMaster
    {
        public decimal ID { get; set; }
        public string FromID { get; set; }
        public Nullable<int> MailType { get; set; }
        public Nullable<int> SendingType { get; set; }
        public string ToList { get; set; }
        public string MailSubject { get; set; }
        public string MailBody { get; set; }
        public Nullable<int> MailBodyType { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> ScheduleDate { get; set; }
        public string UniqueCode { get; set; }
        public Nullable<bool> IsAdminSent { get; set; }
        public Nullable<int> SBranchID { get; set; }
    }
}
