//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMEnterpriseDB.Models
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class MailTemplates
    {
        public int TemplateID { get; set; }
        public Nullable<int> TemplateType { get; set; }
        public string TemplateTitle { get; set; }
        public string TemplateBody { get; set; }
        public string TableRowTamplete { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Subject { get; set; }
        public string AdminSubject { get; set; }
        public Nullable<int> SBranchID { get; set; }
    }
}
