//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMEnterpriseDB.Models
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class MessageMaster
    {
        public int MessageID { get; set; }
        public string MessageTitle { get; set; }
        public string MessageBody { get; set; }
        public Nullable<int> SenderID { get; set; }
        public Nullable<int> SenderType { get; set; }
        public Nullable<int> RecieverID { get; set; }
        public Nullable<int> RecieverType { get; set; }
        public Nullable<System.DateTime> SendDate { get; set; }
        public Nullable<int> IsRead { get; set; }
        public Nullable<System.DateTime> ReadDate { get; set; }
        public Nullable<int> ParentMessageID { get; set; }
        public Nullable<int> MainMailThreadID { get; set; }
        public Nullable<bool> IsShow { get; set; }
        public string Attachments { get; set; }
    }
}
