//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMEnterpriseDB.Models
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class NoticeBoard
    {
        public int NoticeID { get; set; }
        public string NoticeTitle { get; set; }
        public string NoticeDescription { get; set; }
        public Nullable<System.DateTime> NoticeStartDate { get; set; }
        public Nullable<System.DateTime> NoticeEndDate { get; set; }
        public Nullable<int> SBranchID { get; set; }
        public Nullable<int> ApplicableFor { get; set; }
        public Nullable<int> NoticeLevel { get; set; }
        public string ClassesIncludedIDs { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> IsSMSSent { get; set; }
        public string SMSSentTo { get; set; }
        public string AssociatedIDs { get; set; }
    }
}
