//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMEnterpriseDB.Models
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class NotificationMaster
    {
        public int NotificationID { get; set; }
        public Nullable<int> RecieverType { get; set; }
        public Nullable<int> NotificationType { get; set; }
        public string NotificationText { get; set; }
        public Nullable<System.DateTime> NotificationDateTime { get; set; }
        public Nullable<int> RecieverID { get; set; }
        public Nullable<int> SBranchID { get; set; }
        public string Result { get; set; }
    }
}
