//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMEnterpriseDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderMaster
    {
        public decimal OrderID { get; set; }
        public string OrderNumber { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> ProviderID { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> ScheduledPickup { get; set; }
        public Nullable<int> OfferID { get; set; }
        public Nullable<decimal> OrderAmount { get; set; }
        public Nullable<decimal> OfferDiscount { get; set; }
        public string OrderAddress { get; set; }
        public Nullable<int> OrderStatus { get; set; }
        public string DeliveredBy { get; set; }
        public string DeliveryMobileNo { get; set; }
        public string DeliveredTo { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<System.DateTime> EstimatedDeliveryDate { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> DayCount { get; set; }
        public Nullable<int> PaymentStatus { get; set; }
        public Nullable<bool> IsUrgent { get; set; }
        public string PaymentDetails { get; set; }
        public Nullable<int> PaymentMode { get; set; }
        public Nullable<decimal> HomeDeliveryCharges { get; set; }
        public Nullable<decimal> UrgentCharges { get; set; }
        public Nullable<System.DateTime> ShippingDateTime { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> OperationBy { get; set; }
    }
}
