//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMEnterpriseDB.Models
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class ParentDiary
    {
        public int PBID { get; set; }
        public Nullable<int> TeacherID { get; set; }
        public Nullable<int> TeacherType { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<System.DateTime> PBDate { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<int> IsRead { get; set; }
        public Nullable<int> MasterID { get; set; }
        public Nullable<int> ClassID { get; set; }
        public Nullable<int> SectionID { get; set; }
        public Nullable<int> SubjectID { get; set; }
    }
}
