//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMEnterpriseDB.Models
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class ParentMaster
    {
        public int ParentID { get; set; }
        public string FatherName { get; set; }
        public string FatherOccupationID { get; set; }
        public string FatherEducationID { get; set; }
        public string FatherMobileNo { get; set; }
        public string FatherEmailID { get; set; }
        public string FatherBloodGroup { get; set; }
        public string MotherName { get; set; }
        public string MotherOccupationID { get; set; }
        public string MotherEducationID { get; set; }
        public string MotherMobileNo { get; set; }
        public string MotherEmailID { get; set; }
        public string MotherBloodGroup { get; set; }
        public string Padd_HouseNo { get; set; }
        public string Padd_Street { get; set; }
        public string Padd_Area { get; set; }
        public string Padd_Sector { get; set; }
        public string Padd_PinCode { get; set; }
        public string Padd_District { get; set; }
        public string Padd_State { get; set; }
        public string Padd_Country { get; set; }
        public string HomeLandLineNo { get; set; }
        public Nullable<int> SBranchID { get; set; }
        public string FatherImage { get; set; }
        public string MotherImage { get; set; }
        public Nullable<System.DateTime> FatherDOB { get; set; }
        public Nullable<System.DateTime> MotherDOB { get; set; }
        public string AccessCardNo { get; set; }
        public Nullable<decimal> AnnualIncome { get; set; }
    }
}
