//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMEnterpriseDB.Models
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class PaymentDetails
    {
        public int CollectionID { get; set; }
        public Nullable<int> PaymentID { get; set; }
        public Nullable<int> FeeTypeID { get; set; }
        public Nullable<int> PayeeID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> DiscPer { get; set; }
        public Nullable<decimal> DiscAmt { get; set; }
        public Nullable<decimal> NetApplicablePayment { get; set; }
        public Nullable<decimal> PaymentRecieved { get; set; }
        public string Year { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<int> SBranchID { get; set; }
        public Nullable<int> DuesPaidCount { get; set; }
        public Nullable<decimal> Adjustment { get; set; }
        public string PaymentDetail { get; set; }
    }
}
