//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMEnterpriseDB.Models
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class PerformanceParameterMaster
    {
        public int ParamID { get; set; }
        public Nullable<int> MainParamID { get; set; }
        public string ParamName { get; set; }
        public string ParamDesc { get; set; }
        public Nullable<int> ParamType { get; set; }
        public Nullable<int> SBranchID { get; set; }
    }
}
