//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMEnterpriseDB.Models
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class PerformanceParameterValues
    {
        public int ParamValID { get; set; }
        public Nullable<int> EvaluationID { get; set; }
        public Nullable<int> StudentSessionID { get; set; }
        public Nullable<int> ParamID { get; set; }
        public string ParamKey { get; set; }
        public string ParamValue { get; set; }
        public string Grade { get; set; }
    }
}
