//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMEnterpriseDB.Models
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class Permissions
    {
        public int PermissionId { get; set; }
        public string Permission1 { get; set; }
    }
    [Serializable]
    public class LoginDetails
    {
        public string UserName { get; set; }
        public string Password { get; set; }
        public string EmailID { get; set; }
        public int UserID { get; set; }
        public int UserType { get; set; }
        public string UniqueCode { get; set; }
        public int SBranchID { get; set; }

    }
}
