//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMEnterpriseDB.Models
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class ProductMaster
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Benifits { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> MinQty { get; set; }
        public Nullable<decimal> PackingSize { get; set; }
        public Nullable<int> PackingSizeUnit { get; set; }
        public Nullable<int> Form { get; set; }
        public Nullable<decimal> MRP { get; set; }
        public Nullable<decimal> OurPrice { get; set; }
        public string Doses { get; set; }
        public string Contraindication { get; set; }
        public Nullable<int> IngredientsType { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public string ImagePath { get; set; }
        public Nullable<bool> IsAvailableForSell { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<bool> isApproved { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
