//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMEnterpriseDB.Models
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class QuestionBankMaster
    {
        public int QuestionID { get; set; }
        public Nullable<int> ChapterID { get; set; }
        public Nullable<int> TopicID { get; set; }
        public Nullable<int> QuestionType { get; set; }
        public Nullable<int> Complexity { get; set; }
        public string QuestionText { get; set; }
        public string Option1 { get; set; }
        public string Option2 { get; set; }
        public string Option3 { get; set; }
        public string Option4 { get; set; }
        public string Answer { get; set; }
        public Nullable<int> SBranchID { get; set; }
    }
}
