//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMEnterpriseDB.Models
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class QuotaMaster
    {
        public int QuotaID { get; set; }
        public string QuotaName { get; set; }
        public string Description { get; set; }
        public Nullable<int> NumberOfStudents { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<int> SBranchID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> SequenceNo { get; set; }
    }
}
