//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMEnterpriseDB.Models
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class SBranchMaster
    {
        public int SBranchID { get; set; }
        public string BranchName { get; set; }
        public string Logo { get; set; }
        public string ContactNo { get; set; }
        public string EmailID { get; set; }
        public string Address { get; set; }
        public string PrincipalName { get; set; }
        public string PrincipalMobile { get; set; }
        public string PrincipalEmail { get; set; }
        public string BranchSchoolName { get; set; }
        public string TagLine { get; set; }
    }
}
