//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMEnterpriseDB.Models
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class SchoolDetails
    {
        public int SchoolID { get; set; }
        public string PrincipalName { get; set; }
        public string SchoolName { get; set; }
        public string Address { get; set; }
        public string PhoneNo { get; set; }
        public string EmailID { get; set; }
    }
}
