//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMEnterpriseDB.Models
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class SMSBalanceMaster
    {
        public int SMSBalID { get; set; }
        public Nullable<int> SMSCredited { get; set; }
        public Nullable<System.DateTime> RechargeDate { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public Nullable<int> SBranchID { get; set; }
    }
}
