//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMEnterpriseDB.Models
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class SMSFailureLog
    {
        public int RecID { get; set; }
        public Nullable<int> SMSType { get; set; }
        public Nullable<int> RecieverType { get; set; }
        public Nullable<int> RecieverID { get; set; }
        public string MobileNumber { get; set; }
        public string SMSText { get; set; }
        public string ReasonFailure { get; set; }
        public Nullable<System.DateTime> SMSDateTime { get; set; }
    }
}
