//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMEnterpriseDB.Models
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class SMSSendingDetails
    {
        public int SMSSentID { get; set; }
        public Nullable<int> SMSSendingID { get; set; }
        public string SMSSendNumber { get; set; }
        public Nullable<int> RecieverType { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> SMSSentDate { get; set; }
    }
}
