//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMEnterpriseDB.Models
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class SMSSendingMaster
    {
        public int SMSSendingID { get; set; }
        public Nullable<int> SMSTemplateID { get; set; }
        public Nullable<int> SMSTypeID { get; set; }
        public Nullable<System.DateTime> SMSSendDate { get; set; }
        public string TemplateText { get; set; }
        public string RecieverCatIDs { get; set; }
        public string Title { get; set; }
        public Nullable<int> ReadStatus { get; set; }
        public Nullable<int> SBranchID { get; set; }
    }
}
