//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMEnterpriseDB.Models
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class StudentMaster
    {
        public int StudentID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<int> Gender { get; set; }
        public Nullable<int> Nationality { get; set; }
        public Nullable<int> ReligionID { get; set; }
        public Nullable<System.DateTime> DOJ { get; set; }
        public string EmailID { get; set; }
        public Nullable<int> Category { get; set; }
        public string Disability { get; set; }
        public Nullable<int> AdmissionRoute { get; set; }
        public string BloodGroup { get; set; }
        public Nullable<int> MotherTongueID { get; set; }
        public string PassportNo { get; set; }
        public Nullable<int> House { get; set; }
        public string BusNo { get; set; }
        public string GuardianName { get; set; }
        public Nullable<int> RelationWithGuardian { get; set; }
        public string GuardianMobileNo { get; set; }
        public string GuardianEmail { get; set; }
        public string Cadd_HouseNo { get; set; }
        public string Cadd_Street { get; set; }
        public Nullable<int> Cadd_AreaCode { get; set; }
        public string Cadd_Sector { get; set; }
        public string Cadd_PinCode { get; set; }
        public Nullable<int> Cadd_DistrictCode { get; set; }
        public Nullable<int> Cadd_StateCode { get; set; }
        public Nullable<int> Cadd_CountryCode { get; set; }
        public string RoleModel { get; set; }
        public string Ambition { get; set; }
        public string ExtraCurricular { get; set; }
        public string Allergic_Medicine { get; set; }
        public string VehicleNo { get; set; }
        public string DriverName { get; set; }
        public string DriverMobileNo { get; set; }
        public string AddressProof { get; set; }
        public string BirthCertificate { get; set; }
        public string CategoryCertificate { get; set; }
        public string Photo { get; set; }
        public string TransferCertificate { get; set; }
        public Nullable<int> SBranchID { get; set; }
        public Nullable<bool> IsAdmissionComplete { get; set; }
        public Nullable<int> AdmissionBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> VehicleRouteID { get; set; }
        public Nullable<int> StopID { get; set; }
        public Nullable<int> HostelRoomID { get; set; }
        public string AccessCardNo { get; set; }
        public Nullable<int> NotificationSMSTo { get; set; }
        public string BusRouteNoMini { get; set; }
        public string AadharCardNo { get; set; }
        public string SchoolUID { get; set; }
        public string MiniAddress { get; set; }
    }
}
