//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMEnterpriseDB.Models
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class StudentAttendanceMasterT
    {
        public int StudentID { get; set; }
        public Nullable<int> SBranchID { get; set; }
        public Nullable<int> ClassID { get; set; }
        public Nullable<int> SectionID { get; set; }
        public string FYear { get; set; }
        public string Month { get; set; }
        public Nullable<double> D1 { get; set; }
        public Nullable<double> D2 { get; set; }
        public Nullable<double> D3 { get; set; }
        public Nullable<double> D4 { get; set; }
        public Nullable<double> D5 { get; set; }
        public Nullable<double> D6 { get; set; }
        public Nullable<double> D7 { get; set; }
        public Nullable<double> D8 { get; set; }
        public Nullable<double> D9 { get; set; }
        public Nullable<double> D10 { get; set; }
        public Nullable<double> D11 { get; set; }
        public Nullable<double> D12 { get; set; }
        public Nullable<double> D13 { get; set; }
        public Nullable<double> D14 { get; set; }
        public Nullable<double> D15 { get; set; }
        public Nullable<double> D16 { get; set; }
        public Nullable<double> D17 { get; set; }
        public Nullable<double> D18 { get; set; }
        public Nullable<double> D19 { get; set; }
        public Nullable<double> D20 { get; set; }
        public Nullable<double> D21 { get; set; }
        public Nullable<double> D22 { get; set; }
        public Nullable<double> D23 { get; set; }
        public Nullable<double> D24 { get; set; }
        public Nullable<double> D25 { get; set; }
        public Nullable<double> D26 { get; set; }
        public Nullable<double> D27 { get; set; }
        public Nullable<double> D28 { get; set; }
        public Nullable<double> D29 { get; set; }
        public Nullable<double> D30 { get; set; }
        public Nullable<double> D31 { get; set; }
        public Nullable<double> Total { get; set; }
        public Nullable<double> TotalDays { get; set; }
    }
}
