//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMEnterpriseDB.Models
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class Student_Session
    {
        public int StudentSessionUID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> ClassID { get; set; }
        public Nullable<int> SectionID { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<int> Status { get; set; }
        public string RollNo { get; set; }
        public Nullable<int> SBranchID { get; set; }
        public Nullable<int> QuotaID { get; set; }
        public Nullable<int> FeePaymentMode { get; set; }
        public Nullable<int> SessionID { get; set; }
        public Nullable<int> HouseID { get; set; }
    }
}
