//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMEnterpriseDB.Models
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class SubjectMasterT
    {
        public int SubjectID { get; set; }
        public string SubjectName { get; set; }
        public Nullable<bool> IsOptionalsubject { get; set; }
        public string LinkID { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> GroupID { get; set; }
        public string SubjectCode { get; set; }
        public Nullable<int> MainSubID { get; set; }
        public Nullable<int> SubjectType { get; set; }
    }
    [Serializable]
    public class SubSubjectTypes
    {
        public int TypeID { get; set; }
        public string TypeName { get; set; }
        public int SBranchID { get; set; }

    }
}
