//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMEnterpriseDB.Models
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class TeacherSubstitutionMaster
    {
        public int SubstitutionID { get; set; }
        public Nullable<int> ReplacedTeacherID { get; set; }
        public Nullable<int> ReplacingTeacherID { get; set; }
        public Nullable<int> PeriodID { get; set; }
        public Nullable<int> DayID { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public Nullable<int> NewSubjectID { get; set; }
        public Nullable<int> ClassID { get; set; }
        public Nullable<int> SectionID { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> SBranchID { get; set; }
    }
}
