//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMEnterpriseDB.Models
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class Teacher_Subject
    {
        public int TSID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public Nullable<int> EducationLevelID { get; set; }
        public Nullable<int> GroupID { get; set; }
    }
}
