//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMEnterpriseDB.Models
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class TopicMaster
    {
        public int TopicID { get; set; }
        public Nullable<int> ChapterID { get; set; }
        public string TopicName { get; set; }
        public string TopicDescription { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<int> SequenceNo { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<decimal> Duration { get; set; }
        public string ReferanceBook { get; set; }
        public Nullable<int> Marks { get; set; }
        public Nullable<int> EvaluationID { get; set; }
        public Nullable<System.DateTime> CompleteDate { get; set; }
        public Nullable<int> CompleateLacture { get; set; }
    }
}
