//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMEnterpriseDB.Models
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class TransportRouteDetails
    {
        public int StopID { get; set; }
        public Nullable<int> RouteID { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<int> StateID { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> AreaID { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
        public Nullable<System.TimeSpan> TimeSecond { get; set; }
        public Nullable<int> HaltDuration { get; set; }
        public Nullable<int> SequenceNo { get; set; }
        public Nullable<System.TimeSpan> TimeR { get; set; }
        public Nullable<System.TimeSpan> TimeRSecond { get; set; }
        public Nullable<int> HaltDurationR { get; set; }
        public Nullable<int> SequenceNoR { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<decimal> Rate { get; set; }
    }
}
