//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMEnterpriseDB.Models
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class Transport_Vehicle_Route
    {
        public int VehicleRouteID { get; set; }
        public Nullable<int> VehicleID { get; set; }
        public Nullable<int> RouteID { get; set; }
        public Nullable<int> DelayFromRouteTime { get; set; }
        public Nullable<int> ShiftType { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> SBranchID { get; set; }
    }
}
