//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMEnterpriseDB.Models
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class TransportHostalAllocationDelocation
    {
        public int THChangeID { get; set; }
        public Nullable<int> ChangeType { get; set; }
        public Nullable<int> UserType { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> SessionID { get; set; }
        public Nullable<int> KeyID { get; set; }
    }
}
