//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMEnterpriseDB.Models
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class Transport_Vehicle_Route_Details
    {
        public Nullable<int> VehicleRouteDetailID { get; set; }
        public int VehicleRouteID { get; set; }
        public Nullable<int> StopID { get; set; }
        public Nullable<int> Halt { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
        public Nullable<int> SequenceNo { get; set; }
        public Nullable<int> HaltR { get; set; }
        public Nullable<System.TimeSpan> TimeR { get; set; }
        public Nullable<int> SequenceNoR { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
