//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMEnterpriseDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_ShippingAddress
    {
        public int ShippingID { get; set; }
        public Nullable<decimal> UserID { get; set; }
        public string ShippingName { get; set; }
        public string ShippingContactNumber { get; set; }
        public string ShippingFax { get; set; }
        public string ShippingAddress { get; set; }
        public string ShippingPin { get; set; }
        public Nullable<int> ShippingCountry { get; set; }
        public Nullable<int> ShippingStateName { get; set; }
        public Nullable<int> ShippingCity { get; set; }
        public Nullable<int> ShippingArea { get; set; }
        public Nullable<bool> IsDefault { get; set; }
    }
}
