//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMEnterpriseDB.Models
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class User_Details
    {
        public decimal UserID { get; set; }
        public string FullName { get; set; }
        public string ContactAddress { get; set; }
        public string MobileNumber { get; set; }
        public string LandlineNumber { get; set; }
        public string AboutYourSelf { get; set; }
        public string Pin { get; set; }
        public Nullable<int> City { get; set; }
        public Nullable<int> StateName { get; set; }
        public Nullable<int> Country { get; set; }
        public Nullable<System.DateTime> RegistrationDateTime { get; set; }
    }
}
