//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMEnterpriseDB.Models
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class VehicleDetails
    {
        public int VehicleID { get; set; }
        public string VehicleNumber { get; set; }
        public string RegistrationNumber { get; set; }
        public Nullable<int> VehicleCapacity { get; set; }
        public string ContactPerson { get; set; }
        public string ContactNumber { get; set; }
        public Nullable<int> VehicleType { get; set; }
        public Nullable<System.DateTime> InsuranceRenewalDate { get; set; }
        public Nullable<int> DriverID { get; set; }
        public Nullable<int> ConductorID { get; set; }
        public Nullable<int> VehicleCondition { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public string VehicleImage { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> SBranchID { get; set; }
        public string DeviceID { get; set; }
    }
}
